# infra/prometheus/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: [ 'localhost:9090' ]

- job_name: 'prism-services'
  static_configs:
  - targets: [ 'auth-service:8080', 'user-service:8080', 'notification-service:8080', 'file-service:8080', 'invitation-service:8080' ]

- job_name: 'traefik'
  static_configs:
  - targets: [ 'traefik:8082' ]
  metrics_path: /metrics

- job_name: 'cadvisor'
  static_configs:
  - targets: [ 'cadvisor:8080' ]
